### ISSUE TITLE
rename deploy to .deploy

### ISSUE THREAD

**Issue by cyclops24** [AYCRAL/meteor-deployment#2]
Hi man,
I think it's better to rename deploy folder to .deploy because any folder in Meteor.js accessible from client except: server, hidden and some other special folder.

**Comment by cristiandley** [comment]
Ready

https://github.com/AYCRAL/meteor-deployment/commit/75029f16c700b5d5b2f811b80372f707827a63b1

**Comment by cyclops24** [comment]
Thanks man 👍
